USE PriceSolutionsBD
INSERT INTO Producto VALUES
(1,'Ranchero - Primerba\, Paste',26.9,'Cras mi pede\, malesuada in\, imperdiet et\, commodo vulputate\, justo. In blandit ultrices enim. Lorem ipsum dolor sit amet\, consectetuer adipiscing elit.'),
(2,'Wine - Chateau Aqueria Tavel',17.54,'Integer ac leo. Pellentesque ultrices mattis odio. Donec vitae nisi.'),
(3,'Mushroom - Crimini',34.9,'Fusce posuere felis sed lacus. Morbi sem mauris\, laoreet ut\, rhoncus aliquet\, pulvinar sed\, nisl. Nunc rhoncus dui vel sem.'),
(4,'Transfer Sheets',13.39,'Cras non velit nec nisi vulputate nonummy. Maecenas tincidunt lacus at velit. Vivamus vel nulla eget eros elementum pellentesque.'),
(5,'Foil - 4oz Custard Cup',37.54,'Pellentesque at nulla. Suspendisse potenti. Cras in purus eu magna vulputate luctus.'),
(6,'Truffle Cups - Red',36.32,'Vestibulum ac est lacinia nisi venenatis tristique. Fusce congue\, diam id ornare imperdiet\, sapien urna pretium nisl\, ut volutpat sapien arcu sed augue. Aliquam erat volutpat.'),
(7,'Rice Paper',23.23,'Lorem ipsum dolor sit amet\, consectetuer adipiscing elit. Proin risus. Praesent lectus.'),
(8,'Pork - Ground',28.39,'Phasellus sit amet erat. Nulla tempus. Vivamus in felis eu sapien cursus vestibulum.'),
(9,'Beer - Moosehead',39.08,'In congue. Etiam justo. Etiam pretium iaculis justo.'),
(10,'Chicken - Wieners',16.73,'In hac habitasse platea dictumst. Etiam faucibus cursus urna. Ut tellus.'),
(11,'Flour - Strong Pizza',12.85,'Curabitur in libero ut massa volutpat convallis. Morbi odio odio\, elementum eu\, interdum eu\, tincidunt in\, leo. Maecenas pulvinar lobortis est.'),
(12,'Oil - Macadamia',4.77,'In sagittis dui vel nisl. Duis ac nibh. Fusce lacus purus\, aliquet at\, feugiat non\, pretium quis\, lectus.'),
(13,'Chinese Foods - Chicken Wing',34.72,'Morbi non lectus. Aliquam sit amet diam in magna bibendum imperdiet. Nullam orci pede\, venenatis non\, sodales sed\, tincidunt eu\, felis.'),
(14,'Bread - Pumpernickel',4.66,'Etiam vel augue. Vestibulum rutrum rutrum neque. Aenean auctor gravida sem.'),
(15,'Coffee - Decafenated',37.3,'Maecenas leo odio\, condimentum id\, luctus nec\, molestie sed\, justo. Pellentesque viverra pede ac diam. Cras pellentesque volutpat dui.'),
(16,'Tomatoes Tear Drop',37.66,'Phasellus in felis. Donec semper sapien a libero. Nam dui.'),
(17,'Oil - Olive\, Extra Virgin',8.2,'Duis aliquam convallis nunc. Proin at turpis a pede posuere nonummy. Integer non velit.'),
(18,'Jicama',36.72,'Nullam porttitor lacus at turpis. Donec posuere metus vitae ipsum. Aliquam non mauris.'),
(19,'Bread Country Roll',34.37,'Nam ultrices\, libero non mattis pulvinar\, nulla pede ullamcorper augue\, a suscipit nulla elit ac nulla. Sed vel enim sit amet nunc viverra dapibus. Nulla suscipit ligula in lacus.'),
(20,'Onions - Spanish',35.12,'In hac habitasse platea dictumst. Etiam faucibus cursus urna. Ut tellus.'),
(21,'Cheese - Fontina',39.78,'Pellentesque at nulla. Suspendisse potenti. Cras in purus eu magna vulputate luctus.'),
(22,'Pea - Snow',35.05,'Suspendisse potenti. In eleifend quam a odio. In hac habitasse platea dictumst.'),
(23,'Garbag Bags - Black',32.95,'Morbi porttitor lorem id ligula. Suspendisse ornare consequat lectus. In est risus\, auctor sed\, tristique in\, tempus sit amet\, sem.'),
(24,'Bread Country Roll',31.3,'Aenean fermentum. Donec ut mauris eget massa tempor convallis. Nulla neque libero\, convallis eget\, eleifend luctus\, ultricies eu\, nibh.'),
(25,'Scrubbie - Scotchbrite Hand Pad',5.17,'Quisque porta volutpat erat. Quisque erat eros\, viverra eget\, congue eget\, semper rutrum\, nulla. Nunc purus.'),
(26,'Octopus - Baby\, Cleaned',32.44,'In quis justo. Maecenas rhoncus aliquam lacus. Morbi quis tortor id nulla ultrices aliquet.'),
(27,'Plate Foam Laminated 9in Blk',27.82,'Curabitur at ipsum ac tellus semper interdum. Mauris ullamcorper purus sit amet nulla. Quisque arcu libero\, rutrum ac\, lobortis vel\, dapibus at\, diam.'),
(28,'Pork - Tenderloin\, Frozen',2.36,'Praesent id massa id nisl venenatis lacinia. Aenean sit amet justo. Morbi ut odio.'),
(29,'Tea - Mint',35.84,'Suspendisse potenti. In eleifend quam a odio. In hac habitasse platea dictumst.'),
(30,'Coffee Swiss Choc Almond',19.89,'Aliquam quis turpis eget elit sodales scelerisque. Mauris sit amet eros. Suspendisse accumsan tortor quis turpis.'),
(31,'Banana',29.91,'Maecenas leo odio\, condimentum id\, luctus nec\, molestie sed\, justo. Pellentesque viverra pede ac diam. Cras pellentesque volutpat dui.'),
(32,'Cloves - Ground',27.73,'Praesent blandit. Nam nulla. Integer pede justo\, lacinia eget\, tincidunt eget\, tempus vel\, pede.'),
(33,'Flour - Pastry',21.12,'Praesent id massa id nisl venenatis lacinia. Aenean sit amet justo. Morbi ut odio.'),
(34,'Myers Planters Punch',17.39,'Proin interdum mauris non ligula pellentesque ultrices. Phasellus id sapien in sapien iaculis congue. Vivamus metus arcu\, adipiscing molestie\, hendrerit at\, vulputate vitae\, nisl.'),
(35,'Cheese - Parmesan Grated',18.85,'In quis justo. Maecenas rhoncus aliquam lacus. Morbi quis tortor id nulla ultrices aliquet.'),
(36,'Lettuce - Baby Salad Greens',17.14,'Fusce consequat. Nulla nisl. Nunc nisl.'),
(37,'Cheese - Cheddar\, Mild',4.06,'Vestibulum quam sapien\, varius ut\, blandit non\, interdum in\, ante. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Duis faucibus accumsan odio. Curabitur convallis.'),
(38,'Zucchini - Yellow',31.62,'Duis consequat dui nec nisi volutpat eleifend. Donec ut dolor. Morbi vel lectus in quam fringilla rhoncus.'),
(39,'Orange Roughy 6/8 Oz',23.58,'Proin leo odio\, porttitor id\, consequat in\, consequat ut\, nulla. Sed accumsan felis. Ut at dolor quis odio consequat varius.'),
(40,'Veal - Insides Provini',14.98,'Nulla ut erat id mauris vulputate elementum. Nullam varius. Nulla facilisi.'),
(41,'Tomatoes - Plum\, Canned',12.71,'Duis aliquam convallis nunc. Proin at turpis a pede posuere nonummy. Integer non velit.'),
(42,'Seedlings - Mix\, Organic',24.22,'Duis bibendum. Morbi non quam nec dui luctus rutrum. Nulla tellus.'),
(43,'Halibut - Steaks',1.01,'Mauris enim leo\, rhoncus sed\, vestibulum sit amet\, cursus id\, turpis. Integer aliquet\, massa id lobortis convallis\, tortor risus dapibus augue\, vel accumsan tellus nisi eu orci. Mauris lacinia sapien quis libero.'),
(44,'Truffle Cups - Red',28.36,'Cras non velit nec nisi vulputate nonummy. Maecenas tincidunt lacus at velit. Vivamus vel nulla eget eros elementum pellentesque.'),
(45,'Wine - Alicanca Vinho Verde',29.24,'Quisque porta volutpat erat. Quisque erat eros\, viverra eget\, congue eget\, semper rutrum\, nulla. Nunc purus.'),
(46,'Dried Cherries',20.36,'Quisque porta volutpat erat. Quisque erat eros\, viverra eget\, congue eget\, semper rutrum\, nulla. Nunc purus.'),
(47,'Tea - Jasmin Green',2.7,'Fusce posuere felis sed lacus. Morbi sem mauris\, laoreet ut\, rhoncus aliquet\, pulvinar sed\, nisl. Nunc rhoncus dui vel sem.'),
(48,'Chicken - Leg / Back Attach',29.39,'Duis consequat dui nec nisi volutpat eleifend. Donec ut dolor. Morbi vel lectus in quam fringilla rhoncus.'),
(49,'Tarts Assorted',25.55,'Aenean lectus. Pellentesque eget nunc. Donec quis orci eget orci vehicula condimentum.'),
(50,'Beef - Inside Round',22.49,'Maecenas tristique\, est et tempus semper\, est quam pharetra magna\, ac consequat metus sapien ut nunc. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Mauris viverra diam vitae quam. Suspendisse potenti.');