-- SECUENCIAS
CREATE SEQUENCE seq_numSuscriptor
    MINVALUE 1
    START WITH 1
    INCREMENT BY 1
    CACHE 20;

CREATE SEQUENCE seq_idProducto
    MINVALUE 1
    START WITH 1
    INCREMENT BY 1
    CACHE 20;

CREATE SEQUENCE seq_idEmpleado
    MINVALUE 1
    START WITH 1
    INCREMENT BY 1
    CACHE 20;

CREATE SEQUENCE seq_idPedido
    MINVALUE 1
    START WITH 1
    INCREMENT BY 1
    CACHE 20;

--SECUENCIAS DE AUDITORIA
CREATE SEQUENCE seq_idAud_sus
    MINVALUE 1
    START WITH 1
    INCREMENT BY 1
    CACHE 20;

CREATE SEQUENCE seq_idAud_Prod
    MINVALUE 1
    START WITH 1
    INCREMENT BY 1
    CACHE 20;

